typography_spectrum: 0.75887
color:
  brandColors:
    - '#47609d'
    - '#406080'
    - '#3b4e9d'
    - '#404080'
    - '#336699'
  brandStrength: 0.8014933965168893
  lightness: 0.979125197045505
  saturation: 0.5867426232434809
  rhythmicContrast: 0.028525371570140123
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24601
analytics:
  google: null
  facebook: null
  twitter: null
name: flashfoto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
